# Generated by Django 4.2.16 on 2025-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Package Name')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('hotel', models.CharField(max_length=100, verbose_name='Hotel Name')),
                ('days', models.IntegerField(verbose_name='Number of Days')),
                ('nights', models.IntegerField(verbose_name='Number of Nights')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package Price')),
                ('description', models.TextField(verbose_name='Package Description')),
                ('imgname', models.CharField(max_length=100, verbose_name='Image Name')),
            ],
        ),
    ]
